// Generated by ChatGPT and Gemini, mostly

package chatbot

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/signal"
	"sort"
	"stream-chatbot/common"
	"stream-chatbot/player"
	overlay "stream-chatbot/web"
	"strconv"
	"strings"
	"syscall"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/gempir/go-twitch-irc/v4"
)

var twitchToken string
var userLastSearch = make(map[string][]player.Track)

type PollPostData struct {
	BroadcasterId              string           `json:"broadcaster_id"`
	PollTitle                  string           `json:"title"`
	Choices                    []PollPostChoice `json:"choices"`
	ChannelPointsVotingEnabled bool             `json:"channel_points_voting_enabled"`
	ChannelPointsPerVote       int              `json:"channel_points_per_vote"`
	Duration                   int              `json:"duration"`
}

type PollPostChoice struct {
	Title string `json:"title"`
}

type PollGetResponse struct {
	Data []PollGetData `json:"data"`
}

type PollGetData struct {
	ID                         string          `json:"id"`
	BroadcasterID              string          `json:"broadcaster_id"`
	BroadcasterName            string          `json:"broadcaster_name"`
	BroadcasterLogin           string          `json:"broadcaster_login"`
	Title                      string          `json:"title"`
	Choices                    []PollGetChoice `json:"choices"`
	ChannelPointsVotingEnabled bool            `json:"channel_points_voting_enabled"`
	ChannelPointsPerVote       int             `json:"channel_points_per_vote"`
	Status                     string          `json:"status"`
	Duration                   int             `json:"duration"`
	StartedAt                  string          `json:"started_at"`
	EndedAt                    string          `json:"ended_at"`
}

type PollGetChoice struct {
	ID                 string `json:"id"`
	Title              string `json:"title"`
	Votes              int    `json:"votes"`
	ChannelPointsVotes int    `json:"channel_points_votes"`
}

func getPoll() (PollGetResponse, error) {
	// Define your URL and data
	url := "https://api.twitch.tv/helix/polls"

	// Create a new GET request
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		log.Println("Error creating request:", err)
		return PollGetResponse{}, err
	}

	// Set the headers
	log.Printf("Length of 'twitchToken': %v\n", len(twitchToken))
	bearerToken := twitchToken
	req.Header.Set("Authorization", "Bearer "+bearerToken)
	req.Header.Set("Client-Id", common.ChatbotCreds["ClientID"])

	// Set the query parameters
	q := req.URL.Query()
	q.Add("broadcaster_id", common.ChatbotCreds["BroadcasterID"])
	q.Add("status", "ACTIVE")
	req.URL.RawQuery = q.Encode()

	// Send the request with a client
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		log.Println("Error sending request:", err)
		return PollGetResponse{}, err
	}
	defer resp.Body.Close()

	// Optionally, handle the response
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Println("Error reading response body:", err)
		return PollGetResponse{}, err
	}

	log.Println("Response status:", resp.StatusCode)

	// Parse the JSON data into a Data struct
	var jsonResponse PollGetResponse
	err = json.Unmarshal(body, &jsonResponse)
	if err != nil {
		log.Println("Error parsing JSON data", err)
		return PollGetResponse{}, err
	}

	return jsonResponse, nil
}

func getPollResults() string {
	jsonResponse, err := getPoll()
	if err != nil {
		errorMessage := "Error getting poll with getPoll()"
		log.Println(errorMessage, err)
		return errorMessage
	}

	var recentPoll string

	// Access the first element of the array
	if len(jsonResponse.Data) > 0 {
		firstValue := jsonResponse.Data[0]
		recentPoll += "Latest poll data! //// Poll title: \"" + firstValue.Title + "\" //// Choices:"
		for _, choice := range firstValue.Choices {
			recentPoll += " // \"" + choice.Title + "\": " + fmt.Sprint(choice.Votes)
		}
	} else {
		emptyMessage := "Array is empty"
		log.Println(emptyMessage)
		return emptyMessage
	}

	return recentPoll
}

func isPollActive() bool {
	jsonResponse, err := getPoll()
	if err != nil {
		log.Println("Error getting poll with getPoll()", err)
	}

	var isActive bool

	// Access the first element of the array
	if len(jsonResponse.Data) > 0 {
		firstValue := jsonResponse.Data[0]
		if firstValue.Status == "ACTIVE" {
			isActive = true
		} else {
			isActive = false
		}
	} else {
		log.Println("Array is empty")
		isActive = false
	}

	return isActive
}

func sendPoll(pollText string) string {
	log.Println("pollText: " + pollText)

	pollLength := len(strings.Split(pollText, "//"))
	log.Println("pollLength:", pollLength)
	if pollLength < 3 {
		errorMessage := "Not enough choices"
		log.Println(errorMessage)
		return errorMessage
	} else if pollLength > 6 {
		errorMessage := "Too many choices"
		log.Println(errorMessage)
		return errorMessage
	}

	var question string
	var choice string
	choices := []PollPostChoice{}

	for index, phrase := range strings.Split(pollText, "//") {
		if index == 0 {
			// Needs to be 60 chars or less
			if len(strings.TrimSpace(phrase)) > 60 {
				question = strings.TrimSpace(phrase)[0:60]
			} else {
				question = strings.TrimSpace(phrase)
			}
			log.Println("Identified question as:", question)
		} else {
			// Needs to be 25 chars or less
			if len(strings.TrimSpace(phrase)) > 25 {
				choice = strings.TrimSpace(phrase)[0:25]
			} else {
				choice = strings.TrimSpace(phrase)
			}
			log.Printf("Identified choice %s as: %s\n", fmt.Sprint(index), choice)
			choices = append(choices, PollPostChoice{Title: choice})
		}
	}

	// Define your URL and data
	url := "https://api.twitch.tv/helix/polls"
	data := PollPostData{
		BroadcasterId:              common.ChatbotCreds["BroadcasterID"],
		PollTitle:                  question,
		Choices:                    choices,
		ChannelPointsVotingEnabled: true,
		ChannelPointsPerVote:       100,
		Duration:                   60,
	}

	// Marshal the data to JSON
	jsonData, err := json.Marshal(data)
	if err != nil {
		errorMessage := "Error marshalling JSON"
		log.Println(errorMessage, err)
		return errorMessage
	}

	// Create a new POST request
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		errorMessage := "Error creating request"
		log.Println(errorMessage, err)
		return errorMessage
	}

	// Set the headers
	bearerToken := twitchToken
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+bearerToken)
	req.Header.Set("Client-Id", common.ChatbotCreds["ClientID"])

	// Send the request with a client
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		errorMessage := "Error sending request"
		log.Println(errorMessage, err)
		return errorMessage
	}
	defer resp.Body.Close()

	// Optionally, handle the response
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		errorMessage := "Error reading response body"
		log.Println(errorMessage, err)
		return errorMessage
	}

	log.Println("Response status:", resp.StatusCode)
	log.Println("Response body:", string(body))

	if resp.StatusCode != 200 {
		return "Error creating poll"
	} else {
		return "Poll created successfully"
	}

}

// Borrowed code for better alphabetizer, case insensitive!
// https://programming-idioms.org/idiom/297/sort-a-list-of-strings-case-insensitively/5458/go

func lessCaseInsensitive(s, t string) bool {
	for {
		if len(t) == 0 {
			return false
		}
		if len(s) == 0 {
			return true
		}
		c, sizec := utf8.DecodeRuneInString(s)
		d, sized := utf8.DecodeRuneInString(t)

		lowerc := unicode.ToLower(c)
		lowerd := unicode.ToLower(d)

		if lowerc < lowerd {
			return true
		}
		if lowerc > lowerd {
			return false
		}

		s = s[sizec:]
		t = t[sized:]
	}
}

func alphabetize(message string) string {
	words := strings.Fields(message)
	sort.Slice(words, func(i, j int) bool { return lessCaseInsensitive(words[i], words[j]) })
	result := strings.Join(words, " ")
	return result
}

// Borrowed some code from Twilio's example for getting inspirational quotes
// https://www.twilio.com/blog/inspire-your-friends-using-go-twilio-messaging

type Response struct {
	Status     string
	StatusCode int
	Method     string
	Body       []byte
}

type ZenQuotes struct {
	Quote  string `json:"q"`
	Author string `json:"a"`
}

func getQuote() string {
	response, err := sendRequest()
	if err != nil {
		log.Fatal(err)
	}

	var message ZenQuotes
	msg := []ZenQuotes{{
		message.Author,
		message.Quote,
	}}

	err = json.Unmarshal(response.Body, &msg)
	if err != nil {
		log.Fatal(err)
	}
	return msg[0].Quote
}

func sendRequest() (*Response, error) {
	r := &Response{}

	httpClient := &http.Client{Timeout: 20 * time.Second}
	zenQuotesUrl := "https://zenquotes.io/api/random"

	req, err := http.NewRequest(http.MethodGet, zenQuotesUrl, nil)
	if err != nil {
		return nil, err
	}

	response, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}

	defer response.Body.Close()

	body, err := io.ReadAll(response.Body)
	if err != nil {
		return nil, err
	}

	r.Status = response.Status
	r.StatusCode = response.StatusCode
	r.Body = body

	return r, nil
}

func Chatbot(TwitchToken string) {
	// Set your Twitch username, OAuth token, and channel to join
	username := common.ChatbotCreds["TwitchUsername"]
	twitchToken = TwitchToken
	channel := common.ChatbotCreds["TwitchChannel"]
	log.Printf("Received token from main module: %s\n", twitchToken[len(twitchToken)-5:])
	fmt.Printf("Using Twitch account: %s\n", username)
	log.Printf("Using Twitch account: %s\n", username)
	fmt.Printf("Attaching to channel: %s\n", channel)
	log.Printf("Attaching to channel: %s\n", channel)

	// Create a new Twitch client
	client := twitch.NewClient(username, "oauth:"+twitchToken)

	// Register a callback for when the bot receives a message
	client.OnPrivateMessage(func(message twitch.PrivateMessage) {
		// Print the message to the console
		log.Printf("[%s] %s: %s\n", message.Channel, message.User.DisplayName, message.Message)

		// You can add your own logic here to respond to messages
		// For example, you can check for specific commands and reply accordingly
		// TODO: Make a function to parse messages using common conditions. Examples:
		//   * startsWith(message.Message, "!string ")
		//   * equals(message.Message, "!string")
		//   * hasArg(message.Message, [eq,lt,gt], int)
		//   * fromUser(message.Message, "user")
		//   * fromRole(message.Message, [bc,mod,vip,sub,fol])
		if message.Message == "!hello" || message.Message == "!hellobot" {
			log.Println("Detected !hello message")
			client.Say(message.Channel, "Hello, "+message.User.DisplayName+"!")
		}
		if message.Message == "!bye" || message.Message == "!byebot" {
			log.Println("Detected !bye message")
			client.Say(message.Channel, "Goodbye, "+message.User.DisplayName+"! I'll miss you!")
		}
		if strings.HasPrefix(message.Message, "!abc ") || strings.HasPrefix(message.Message, "!alpha ") {
			log.Println("Detected !abc message")
			commandText := strings.TrimPrefix(message.Message, "!abc ")
			//TODO: Ensure there is a message after the !abc command to be alphabetized
			client.Say(message.Channel, alphabetize(commandText))
		}
		// Command ideas:
		// !randomize - Randomize the words from the given message.
		// !lore - Print a random line from a text file containing deep conflabermits lore.
		if message.Message == "!quote" || message.Message == "!randomquote" {
			log.Println("Detected !quote message")
			client.Say(message.Channel, "Random quote -- "+getQuote()+".. in bed.")
		}
		if message.Message == "!poll" || message.Message == "!getPoll" || message.Message == "!getPollResults" {
			log.Println("Detected !getPoll message")
			client.Say(message.Channel, getPollResults())
		}
		if strings.HasPrefix(message.Message, "!poll ") {
			log.Println("Detected !poll message")
			if isPollActive() {
				client.Say(message.Channel, "Sorry, a poll is currently active, try again when it's done.")
				//} else if message.User.DisplayName != "conflabermits" {
				//	client.Say(message.Channel, "Sorry, only accepting polls from conflabermits right now!")
			} else {
				client.Say(message.Channel, "Attempting to create a poll for @"+message.User.DisplayName+"...")
				pollText := strings.TrimPrefix(message.Message, "!poll ")
				client.Say(message.Channel, sendPoll(pollText))
			}
		}

		// Handle aliases for !request commands
		msgTextLower := strings.ToLower(message.Message)
		requestAliases := []string{"!add", "!search", "!remove", "!play", "!pause", "!resume", "!skip", "!done", "!queue", "!info", "!limit", "!autoplay"}
		for _, alias := range requestAliases {
			if strings.HasPrefix(msgTextLower, alias+" ") || msgTextLower == alias {
				// Replace the alias with !request <command> preserving original casing for arguments
				message.Message = "!request " + strings.TrimPrefix(alias, "!") + message.Message[len(alias):]
				break
			}
		}

		if strings.HasPrefix(message.Message, "!request ") {
			log.Println("Detected !request message")
			args := strings.Fields(strings.TrimSpace(strings.TrimPrefix(message.Message, "!request ")))
			if len(args) == 0 {
				client.Say(message.Channel, "Usage: !request <add|search|remove|play|pause|resume|skip|done|queue|info|limit|autoplay> (or use !<command> directly)")
				return
			}
			
			subCommand := strings.ToLower(args[0])
			isMod := message.User.Badges["moderator"] == 1 || message.User.Badges["broadcaster"] == 1

			switch subCommand {
			case "add", "search":
				query := strings.Join(args[1:], " ")
				if query == "" {
					msg := "Usage: !request " + subCommand + " <song/link or number>"
					log.Printf("[!request %s] Response: %s\n", subCommand, msg)
					client.Say(message.Channel, msg)
					return
				}

				// Check if query is just a number for a past search
				if subCommand == "add" {
					if idx, err := strconv.Atoi(query); err == nil {
						lastTracks, ok := userLastSearch[message.User.DisplayName]
						if ok && idx >= 1 && idx <= len(lastTracks) {
							track := lastTracks[idx-1]
							err = player.AddTrack(track, isMod)
							if err != nil {
								msg := "Error adding track: " + err.Error()
								log.Printf("[!request add] Response: %s\n", msg)
								client.Say(message.Channel, msg)
								return
							}
							overlay.BroadcastState()
							msg := fmt.Sprintf("Added to queue: %s - %s", track.Artist, track.Title)
							log.Printf("[!request add] Success: %s\n", msg)
							client.Say(message.Channel, msg)
							return
						}
					}
				}

				log.Printf("[!request %s] Searching for '%s'\n", subCommand, query)
				
				go func() {
					tracks, err := player.SearchTrack(query, message.User.DisplayName)
					if err != nil || len(tracks) == 0 {
						msg := "Error or no results: "
						if err != nil {
							msg += err.Error()
						} else {
							msg += "none found"
						}
						log.Printf("[!request %s] Response: %s\n", subCommand, msg)
						client.Say(message.Channel, msg)
						return
					}
					
					// Store for future add
					userLastSearch[message.User.DisplayName] = tracks
					
					if subCommand == "search" {
						var results []string
						for i, t := range tracks {
							results = append(results, fmt.Sprintf("%d. %s - %s", i+1, t.Artist, t.Title))
						}
						msg := "Top results: " + strings.Join(results, " | ") + " (Type !request add 1 to queue)"
						log.Printf("[!request search] Success: %s\n", msg)
						client.Say(message.Channel, msg)
					} else { // add
						track := tracks[0]
						err = player.AddTrack(track, isMod)
						if err != nil {
							msg := "Error adding track: " + err.Error()
							log.Printf("[!request add] Response: %s\n", msg)
							client.Say(message.Channel, msg)
							return
						}
						overlay.BroadcastState()
						msg := fmt.Sprintf("Added to queue: %s - %s", track.Artist, track.Title)
						log.Printf("[!request add] Success: %s\n", msg)
						client.Say(message.Channel, msg)
					}
				}()

			case "remove":
				query := strings.Join(args[1:], " ")
				removedTitle, err := player.RemoveTrack(query, isMod, message.User.DisplayName)
				if err != nil {
					msg := "Error removing track: " + err.Error()
					log.Printf("[!request remove] Response: %s\n", msg)
					client.Say(message.Channel, msg)
				} else {
					overlay.BroadcastState()
					msg := "Removed track: " + removedTitle
					log.Printf("[!request remove] Success: %s\n", msg)
					client.Say(message.Channel, msg)
				}

			case "play":
				if isMod {
					err := player.PlayOrResume()
					if err != nil {
						msg := "Play error: " + err.Error()
						log.Printf("[!request play] Response: %s\n", msg)
						client.Say(message.Channel, msg)
					} else {
						overlay.BroadcastState()
						msg := "Playing!"
						log.Printf("[!request play] Success: %s\n", msg)
						client.Say(message.Channel, msg)
					}
				} else {
					msg := "You do not have permission to control playback."
					log.Printf("[!request play] Response: %s\n", msg)
					client.Say(message.Channel, msg)
				}

			case "pause":
				if isMod {
					err := player.Pause()
					if err != nil {
						msg := "Pause error: " + err.Error()
						log.Printf("[!request pause] Response: %s\n", msg)
						client.Say(message.Channel, msg)
					} else {
						overlay.BroadcastState()
						msg := "Paused."
						log.Printf("[!request pause] Success: %s\n", msg)
						client.Say(message.Channel, msg)
					}
				} else {
					msg := "You do not have permission to control playback."
					log.Printf("[!request pause] Response: %s\n", msg)
					client.Say(message.Channel, msg)
				}

			case "resume":
				if isMod {
					err := player.PlayOrResume()
					if err != nil {
						msg := "Resume error: " + err.Error()
						log.Printf("[!request resume] Response: %s\n", msg)
						client.Say(message.Channel, msg)
					} else {
						overlay.BroadcastState()
						msg := "Resumed!"
						log.Printf("[!request resume] Success: %s\n", msg)
						client.Say(message.Channel, msg)
					}
				} else {
					msg := "You do not have permission to control playback."
					log.Printf("[!request resume] Response: %s\n", msg)
					client.Say(message.Channel, msg)
				}

			case "skip", "done":
				if isMod {
					player.SkipCurrent()
					if player.GetAutoplay() {
						player.PlayOrResume()
					}
					overlay.BroadcastState()
					msg := "Current track skipped!"
					log.Printf("[!request %s] Success: %s\n", subCommand, msg)
					client.Say(message.Channel, msg)
				} else {
					msg := "You do not have permission to skip tracks."
					log.Printf("[!request %s] Response: %s\n", subCommand, msg)
					client.Say(message.Channel, msg)
				}
				
			case "queue":
				q := player.GetQueue()
				if len(q) == 0 {
					msg := "The queue is currently empty."
					log.Printf("[!request queue] Response: %s\n", msg)
					client.Say(message.Channel, msg)
				} else {
					var upNext []string
					for i, t := range q {
						if i >= 3 {
							break
						}
						upNext = append(upNext, fmt.Sprintf("%d. %s - %s", i+1, t.Artist, t.Title))
					}
					msg := "Up next: " + strings.Join(upNext, " | ")
					log.Printf("[!request queue] Response: %s\n", msg)
					client.Say(message.Channel, msg)
				}
				
			case "info":
				t := player.GetCurrentTrack()
				if t == nil {
					msg := "No track is currently playing."
					log.Printf("[!request info] Response: %s\n", msg)
					client.Say(message.Channel, msg)
				} else {
					duration := fmt.Sprintf("%02d:%02d", t.Duration/60, t.Duration%60)
					msg := fmt.Sprintf("Currently playing: %s - %s [%s] (Requested by: %s)", t.Artist, t.Title, duration, t.RequestedBy)
					log.Printf("[!request info] Response: %s\n", msg)
					client.Say(message.Channel, msg)
				}
				
			case "limit":
				if isMod {
					enabled := player.ToggleRateLimit()
					if enabled {
						msg := "Rate limiting is now ENABLED (2 songs / 10 mins)."
						log.Printf("[!request limit] Response: %s\n", msg)
						client.Say(message.Channel, msg)
					} else {
						msg := "Rate limiting is now DISABLED."
						log.Printf("[!request limit] Response: %s\n", msg)
						client.Say(message.Channel, msg)
					}
				} else {
					msg := "You do not have permission to toggle the rate limit."
					log.Printf("[!request limit] Response: %s\n", msg)
					client.Say(message.Channel, msg)
				}

			case "autoplay":
				if isMod {
					enabled := player.ToggleAutoplay()
					if enabled {
						msg := "Autoplay is now ENABLED. The next song will play automatically."
						log.Printf("[!request autoplay] Response: %s\n", msg)
						client.Say(message.Channel, msg)
					} else {
						msg := "Autoplay is now DISABLED. You will need to use !request play between songs."
						log.Printf("[!request autoplay] Response: %s\n", msg)
						client.Say(message.Channel, msg)
					}
				} else {
					msg := "You do not have permission to toggle autoplay."
					log.Printf("[!request autoplay] Response: %s\n", msg)
					client.Say(message.Channel, msg)
				}

			default:
				msg := "Unknown subcommand. Usage: !request <add|search|remove|play|pause|resume|skip|done|queue|info|limit|autoplay> (or use !<command> directly)"
				log.Printf("[!request] Response: %s\n", msg)
				client.Say(message.Channel, msg)
			}
		}
	})

	client.OnConnect(func() {
		client.Say(channel, "conflabermits chatbot started -- Let's GOOOOOO! confla3Nyan confla3Shake confla3Party confla3Spin")
	})

	// Join the specified channel
	client.Join(channel)

	// Connect to Twitch IRC
	err := client.Connect()
	if err != nil {
		log.Fatal(err)
	}

	// Wait for a signal to gracefully shut down the bot
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)
	<-sigChan

	// Disconnect from Twitch IRC on shutdown
	client.Disconnect()
}
